# src/deeprbp/configs/config_model_training.yaml

# Model predictor configuration
model:
  #input_size: 1348
  #output_size: 11459
  num_hidden_layers: 2
  max_node: 1024
  uniform_nodes: True
  node_shrink_factor: 8
  activation_func: "relu"
  learning_rate: 0.001
  optimizer_name: "adamW"
  cuda: true  # Set to true if you want to use GPU

# Training configuration
training:
  epochs: 1000
  batch_size: 128
  print_every: 10  # Print progress every N epochs
  train_val_split: true
  val_fraction: 0.15  # Fraction of training data to reserve for validation
  seed: 0