# src/deeprbp/configs/config_tcga_train.yaml

data_paths:
  rbp_path: "/scratch/jsanchoz/DeepRBP/data/training_module/splitted_datasets/Train/train_RBPs_log2p_tpm.csv"
  isoform_expr_path: "/scratch/jsanchoz/DeepRBP/data/training_module/splitted_datasets/Train/train_trans_log2p_tpm.csv"
  gene_expr_path: "/scratch/jsanchoz/DeepRBP/data/training_module/splitted_datasets/Train/train_gn_tpm.csv"
  metadata_path: "/scratch/jsanchoz/DeepRBP/data/training_module/splitted_datasets/Train/train_phenotype_metadata.csv"

sample_category: "detailed_category"  # The column in metadata to stratify on 
test_fraction: 0.2
getBM_path: "/scratch/jsanchoz/DeepRBP/data/training_module/selected_genes_rbps/getBM.csv"
gene_col_name: "Gene_ID"
trans_col_name: "Transcript_ID"
seed: 42
cuda: True
print_every: 5
train_batch_size: 128
val_batch_size: 256
num_epochs: 10 # 100
num_hidden_layers: 1
hidden1_nodes: 64
uniform_nodes: False
node_shrink_factor: 4
activation_func: relu
learning_rate: 0.001
optimizer_name: adamW
plot_results: True
save_results: True
save_best_model: True