# src/deeprbp/configs/config_hyper_optimization.yaml
train_path_files: '/scratch/jsanchoz/DeepRBP/data/training_module/splitted_datasets/Train'
sample_category: "detailed_category"   
sample_fraction: 0.5
test_fraction: 0.2
getBM_path: "/scratch/jsanchoz/DeepRBP/data/training_module/selected_genes_rbps/getBM.csv"
gene_col_name: "Gene_ID"
trans_col_name: "Transcript_ID"
cuda: True
val_batch_size: 256
plot_results: False