name: Pytorch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2023.5.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libsqlite=3.41.2
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.9.7
  - readline=8.2
  - setuptools=67.7.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.40.0
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - alembic==1.11.0
    - appdirs==1.4.4
    - blinker==1.6.2
    - captum==0.4.0
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - cmaes==0.9.1
    - colorlog==6.7.0
    - contourpy==1.0.7
    - cycler==0.11.0
    - databricks-cli==0.17.7
    - docker==6.1.2
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - flask==2.3.2
    - fonttools==4.39.4
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - greenlet==2.0.2
    - gunicorn==20.1.0
    - hyperopt==0.2.7
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - install==1.3.5
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - llvmlite==0.40.1
    - mako==1.2.4
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-venn==0.11.10
    - mlflow==2.3.2
    - networkx==3.1
    - numba==0.57.1
    - numpy==1.24.3
    - oauthlib==3.2.2
    - openpyxl==3.1.2
    - optuna==3.1.1
    - packaging==23.1
    - pandas==1.5.3
    - pathtools==0.1.2
    - patsy==0.5.3
    - pillow==9.5.0
    - plotly==5.14.1
    - protobuf==4.23.0
    - psutil==5.9.5
    - py4j==0.10.9.7
    - pyaml==23.5.9
    - pyarrow==11.0.0
    - pyjwt==2.7.0
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - qnorm==0.8.1
    - querystring-parser==1.2.4
    - requests==2.30.0
    - scikit-learn==1.2.2
    - scikit-optimize==0.9.0
    - scipy==1.10.1
    - seaborn==0.11.2
    - sentry-sdk==1.23.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==2.0.13
    - sqlparse==0.4.4
    - statannot==0.2.3
    - statannotations==0.6.0
    - statsmodels==0.14.0
    - tabulate==0.9.0
    - tbb==2021.10.0
    - tenacity==8.2.2
    - threadpoolctl==3.1.0
    - torch==1.10.0+cu111
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - umap==0.1.1
    - umap-learn==0.5.4
    - upsetplot==0.9.0
    - urllib3==1.26.15
    - venny4py==1.0.0
    - wandb==0.15.1
    - websocket-client==1.5.1
    - werkzeug==2.3.4
    - zipp==3.15.0

